name: nusic
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  path: ^1.9.0
  audioplayers: ^6.1.0
  sqflite: ^2.3.3+1
  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.6
  flutter_lints: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
